### ISSUE TITLE
Read datetime cell

### ISSUE THREAD

**Issue by VladislavN** [PydPiper/pylightxl#36]
Hi, how i can parse datetime with your library?
![Снимок экрана от 2021-03-25 19-51-35](https://user-images.githubusercontent.com/33672258/112511642-aad1e480-8da3-11eb-8be7-263fd8e794b6.png)
![Снимок экрана от 2021-03-25 19-51-53](https://user-images.githubusercontent.com/33672258/112511648-ac031180-8da3-11eb-9758-f1470f37135b.png)

**Comment by PydPiper** [comment]
Hi Vladislav, thank you for considering using pylightxl. We added datetime handling in v1.54. Please upgrade your pylightxl with `pip install pylightxl -U`

**Comment by spaceofmiah** [comment]
![datefield](https://user-images.githubusercontent.com/37231237/156874134-8ff5240a-3dd2-41f9-b8fd-0ea476fe8ccc.png)

Date field is resulting to numeric value when read. Initially I felt it was a timestamp, but after conversion from timestamp, I get a wrong date. How do I rightly retrieve the date value from a cell. Below is a code sample of what i'm doing:

![shot](https://user-images.githubusercontent.com/37231237/156874366-81078b7d-572b-454e-93cf-bcc9ca8bf645.png)

**Comment by PydPiper** [comment]
@spaceofmiah thank you for letting me know. I took a look and found out that the issue was Microsoft's use of custom styles that are not part of the base xml datetime styles [link](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1)

I released a new version v1.59 please download the new version for support of the custom datetimes.
